import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="891054951439-ke1btjjsh05sschhtdvd72t8g9kumsll.apps.googleusercontent.com">
        <body className={inter.className}>
          <div className="w-full">
            <Header />
            <div className="bg-main h-screen">{children}</div>
          </div>
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
